# This is a basic workflow to help you get started with Actions

name: Scan Security Group

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v4 
        with:
          python-version: "3.8.x"
      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install Dependencies
        run: pipenv install
      - name: run scan only
        env: 
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          # below here don't really need to be in secrets
          PORTS: ${{ secrets.PORTS }}
          CIDR: ${{ secrets.CIDR }}
          EXCLUDED_TAGS_KEY: ${{ secrets.EXCLUDED_TAGS_KEY }}
          EXCLUDED_TAGS_VALUE: ${{ secrets.EXCLUDED_TAGS_VALUE }}
        run: |
          python main.py True
